/* main.c generated by valac 0.28.1, the Vala compiler
 * generated from main.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <stdlib.h>
#include <string.h>
#include <libsoup/soup.h>
#include <json-glib/json-glib.h>
#include <stdio.h>


#define TYPE_DOCKER_GUI (docker_gui_get_type ())
#define DOCKER_GUI(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_DOCKER_GUI, DockerGui))
#define DOCKER_GUI_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_DOCKER_GUI, DockerGuiClass))
#define IS_DOCKER_GUI(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_DOCKER_GUI))
#define IS_DOCKER_GUI_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_DOCKER_GUI))
#define DOCKER_GUI_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_DOCKER_GUI, DockerGuiClass))

typedef struct _DockerGui DockerGui;
typedef struct _DockerGuiClass DockerGuiClass;
typedef struct _DockerGuiPrivate DockerGuiPrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define __vala_SoupBuffer_free0(var) ((var == NULL) ? NULL : (var = (_vala_SoupBuffer_free (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define _json_object_unref0(var) ((var == NULL) ? NULL : (var = (json_object_unref (var), NULL)))
#define __vala_JsonNode_free0(var) ((var == NULL) ? NULL : (var = (_vala_JsonNode_free (var), NULL)))
#define _g_list_free0(var) ((var == NULL) ? NULL : (var = (g_list_free (var), NULL)))
#define _json_array_unref0(var) ((var == NULL) ? NULL : (var = (json_array_unref (var), NULL)))

#define DOCKER_GUI_TYPE_CONTAINER (docker_gui_container_get_type ())
typedef struct _DockerGuiContainer DockerGuiContainer;

struct _DockerGui {
	GtkWindow parent_instance;
	DockerGuiPrivate * priv;
};

struct _DockerGuiClass {
	GtkWindowClass parent_class;
};

struct _DockerGuiContainer {
	gchar* Id;
	gchar* Image;
};


static gpointer docker_gui_parent_class = NULL;

GType docker_gui_get_type (void) G_GNUC_CONST;
enum  {
	DOCKER_GUI_DUMMY_PROPERTY
};
DockerGui* docker_gui_new (void);
DockerGui* docker_gui_construct (GType object_type);
static void docker_gui_setup_treeview (DockerGui* self, GtkTreeView* view);
static void _gtk_main_quit_gtk_widget_destroy (GtkWidget* _sender, gpointer self);
static void docker_gui_get_containers (DockerGui* self, GtkListStore* listmodel);
static void docker_gui_on_row_activated (DockerGui* self, GtkTreeView* treeview, GtkTreePath* path, GtkTreeViewColumn* column);
static void _docker_gui_on_row_activated_gtk_tree_view_row_activated (GtkTreeView* _sender, GtkTreePath* path, GtkTreeViewColumn* column, gpointer self);
static void docker_gui_on_selection (DockerGui* self, GtkTreeSelection* selection);
static void _docker_gui_on_selection_gtk_tree_selection_changed (GtkTreeSelection* _sender, gpointer self);
static void _vala_SoupBuffer_free (SoupBuffer* self);
static JsonNode* _vala_JsonNode_copy (JsonNode* self);
static void _vala_JsonNode_free (JsonNode* self);
static GType docker_gui_container_get_type (void) G_GNUC_CONST G_GNUC_UNUSED;
static DockerGuiContainer* docker_gui_container_dup (const DockerGuiContainer* self);
static void docker_gui_container_free (DockerGuiContainer* self);
static void docker_gui_container_copy (const DockerGuiContainer* self, DockerGuiContainer* dest);
static void docker_gui_container_destroy (DockerGuiContainer* self);
static void docker_gui_get_selection (GtkTreeModel* model, GtkTreeIter* iter, DockerGuiContainer* result);
static gchar* docker_gui_container_to_string (DockerGuiContainer *self);
gint docker_gui_main (gchar** args, int args_length1);


static void _gtk_main_quit_gtk_widget_destroy (GtkWidget* _sender, gpointer self) {
	gtk_main_quit ();
}


DockerGui* docker_gui_construct (GType object_type) {
	DockerGui * self = NULL;
	GtkTreeView* view = NULL;
	GtkTreeView* _tmp0_ = NULL;
	self = (DockerGui*) g_object_new (object_type, NULL);
	gtk_window_set_title ((GtkWindow*) self, "Docker Gui");
	gtk_window_set_default_size ((GtkWindow*) self, 300, 100);
	_tmp0_ = (GtkTreeView*) gtk_tree_view_new ();
	g_object_ref_sink (_tmp0_);
	view = _tmp0_;
	docker_gui_setup_treeview (self, view);
	gtk_container_add ((GtkContainer*) self, (GtkWidget*) view);
	g_signal_connect ((GtkWidget*) self, "destroy", (GCallback) _gtk_main_quit_gtk_widget_destroy, NULL);
	_g_object_unref0 (view);
	return self;
}


DockerGui* docker_gui_new (void) {
	return docker_gui_construct (TYPE_DOCKER_GUI);
}


static void _docker_gui_on_row_activated_gtk_tree_view_row_activated (GtkTreeView* _sender, GtkTreePath* path, GtkTreeViewColumn* column, gpointer self) {
	docker_gui_on_row_activated ((DockerGui*) self, _sender, path, column);
}


static void _docker_gui_on_selection_gtk_tree_selection_changed (GtkTreeSelection* _sender, gpointer self) {
	docker_gui_on_selection ((DockerGui*) self, _sender);
}


static void docker_gui_setup_treeview (DockerGui* self, GtkTreeView* view) {
	GtkListStore* listmodel = NULL;
	GtkListStore* _tmp0_ = NULL;
	GtkTreeView* _tmp1_ = NULL;
	GtkTreeView* _tmp2_ = NULL;
	GtkCellRendererText* _tmp3_ = NULL;
	GtkCellRendererText* _tmp4_ = NULL;
	GtkTreeView* _tmp5_ = NULL;
	GtkCellRendererText* _tmp6_ = NULL;
	GtkCellRendererText* _tmp7_ = NULL;
	GtkTreeView* _tmp8_ = NULL;
	GtkTreeView* _tmp9_ = NULL;
	GtkTreeSelection* _tmp10_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (view != NULL);
	_tmp0_ = gtk_list_store_new (4, G_TYPE_STRING, G_TYPE_STRING, -1);
	listmodel = _tmp0_;
	_tmp1_ = view;
	gtk_tree_view_set_model (_tmp1_, (GtkTreeModel*) listmodel);
	_tmp2_ = view;
	_tmp3_ = (GtkCellRendererText*) gtk_cell_renderer_text_new ();
	g_object_ref_sink (_tmp3_);
	_tmp4_ = _tmp3_;
	gtk_tree_view_insert_column_with_attributes (_tmp2_, -1, "ContainerId", (GtkCellRenderer*) _tmp4_, "text", 0, NULL);
	_g_object_unref0 (_tmp4_);
	_tmp5_ = view;
	_tmp6_ = (GtkCellRendererText*) gtk_cell_renderer_text_new ();
	g_object_ref_sink (_tmp6_);
	_tmp7_ = _tmp6_;
	gtk_tree_view_insert_column_with_attributes (_tmp5_, -1, "Image", (GtkCellRenderer*) _tmp7_, "text", 1, NULL);
	_g_object_unref0 (_tmp7_);
	docker_gui_get_containers (self, listmodel);
	_tmp8_ = view;
	g_signal_connect_object (_tmp8_, "row-activated", (GCallback) _docker_gui_on_row_activated_gtk_tree_view_row_activated, self, 0);
	_tmp9_ = view;
	_tmp10_ = gtk_tree_view_get_selection (_tmp9_);
	g_signal_connect_object (_tmp10_, "changed", (GCallback) _docker_gui_on_selection_gtk_tree_selection_changed, self, 0);
	_g_object_unref0 (listmodel);
}


static void _vala_SoupBuffer_free (SoupBuffer* self) {
	g_boxed_free (soup_buffer_get_type (), self);
}


static gpointer _json_array_ref0 (gpointer self) {
	return self ? json_array_ref (self) : NULL;
}


static JsonNode* _vala_JsonNode_copy (JsonNode* self) {
	return g_boxed_copy (json_node_get_type (), self);
}


static gpointer __vala_JsonNode_copy0 (gpointer self) {
	return self ? _vala_JsonNode_copy (self) : NULL;
}


static gpointer _json_object_ref0 (gpointer self) {
	return self ? json_object_ref (self) : NULL;
}


static void _vala_JsonNode_free (JsonNode* self) {
	g_boxed_free (json_node_get_type (), self);
}


static void docker_gui_get_containers (DockerGui* self, GtkListStore* listmodel) {
	GtkTreeIter iter = {0};
	gchar* uri = NULL;
	gchar* _tmp0_ = NULL;
	SoupSession* session = NULL;
	SoupSession* _tmp1_ = NULL;
	SoupMessage* message = NULL;
	SoupMessage* _tmp2_ = NULL;
	JsonParser* parser = NULL;
	JsonParser* _tmp3_ = NULL;
	SoupMessageBody* _tmp4_ = NULL;
	SoupBuffer* _tmp5_ = NULL;
	SoupBuffer* _tmp6_ = NULL;
	guint8* _tmp7_ = NULL;
	gint _tmp7__length1 = 0;
	JsonArray* jsonContainers = NULL;
	JsonNode* _tmp8_ = NULL;
	JsonArray* _tmp9_ = NULL;
	JsonArray* _tmp10_ = NULL;
	JsonArray* _tmp11_ = NULL;
	GList* _tmp12_ = NULL;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (listmodel != NULL);
	_tmp0_ = g_strdup ("http://localhost:5555/containers/json");
	uri = _tmp0_;
	_tmp1_ = soup_session_new ();
	session = _tmp1_;
	_tmp2_ = soup_message_new ("GET", uri);
	message = _tmp2_;
	soup_session_send_message (session, message);
	_tmp3_ = json_parser_new ();
	parser = _tmp3_;
	_tmp4_ = message->response_body;
	_tmp5_ = soup_message_body_flatten (_tmp4_);
	_tmp6_ = _tmp5_;
	_tmp7_ = _tmp6_->data;
	_tmp7__length1 = (gint) _tmp6_->length;
	json_parser_load_from_data (parser, (const gchar*) _tmp7_, (gssize) (-1), &_inner_error_);
	__vala_SoupBuffer_free0 (_tmp6_);
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_object_unref0 (parser);
		_g_object_unref0 (message);
		_g_object_unref0 (session);
		_g_free0 (uri);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_tmp8_ = json_parser_get_root (parser);
	_tmp9_ = json_node_get_array (_tmp8_);
	_tmp10_ = _json_array_ref0 (_tmp9_);
	jsonContainers = _tmp10_;
	_tmp11_ = jsonContainers;
	_tmp12_ = json_array_get_elements (_tmp11_);
	{
		GList* c_collection = NULL;
		GList* c_it = NULL;
		c_collection = _tmp12_;
		for (c_it = c_collection; c_it != NULL; c_it = c_it->next) {
			JsonNode* _tmp13_ = NULL;
			JsonNode* c = NULL;
			_tmp13_ = __vala_JsonNode_copy0 ((JsonNode*) c_it->data);
			c = _tmp13_;
			{
				JsonObject* o = NULL;
				JsonNode* _tmp14_ = NULL;
				JsonObject* _tmp15_ = NULL;
				JsonObject* _tmp16_ = NULL;
				gchar* Id = NULL;
				JsonObject* _tmp17_ = NULL;
				const gchar* _tmp18_ = NULL;
				gchar* _tmp19_ = NULL;
				gchar* Image = NULL;
				JsonObject* _tmp20_ = NULL;
				const gchar* _tmp21_ = NULL;
				gchar* _tmp22_ = NULL;
				FILE* _tmp23_ = NULL;
				const gchar* _tmp24_ = NULL;
				const gchar* _tmp25_ = NULL;
				GtkListStore* _tmp26_ = NULL;
				GtkTreeIter _tmp27_ = {0};
				GtkListStore* _tmp28_ = NULL;
				GtkTreeIter _tmp29_ = {0};
				const gchar* _tmp30_ = NULL;
				const gchar* _tmp31_ = NULL;
				_tmp14_ = c;
				_tmp15_ = json_node_get_object (_tmp14_);
				_tmp16_ = _json_object_ref0 (_tmp15_);
				o = _tmp16_;
				_tmp17_ = o;
				_tmp18_ = json_object_get_string_member (_tmp17_, "Id");
				_tmp19_ = g_strdup (_tmp18_);
				Id = _tmp19_;
				_tmp20_ = o;
				_tmp21_ = json_object_get_string_member (_tmp20_, "Image");
				_tmp22_ = g_strdup (_tmp21_);
				Image = _tmp22_;
				_tmp23_ = stdout;
				_tmp24_ = Id;
				_tmp25_ = Image;
				fprintf (_tmp23_, "%s - %s\n", _tmp24_, _tmp25_);
				_tmp26_ = listmodel;
				gtk_list_store_append (_tmp26_, &_tmp27_);
				iter = _tmp27_;
				_tmp28_ = listmodel;
				_tmp29_ = iter;
				_tmp30_ = Id;
				_tmp31_ = Image;
				gtk_list_store_set (_tmp28_, &_tmp29_, 0, _tmp30_, 1, _tmp31_, -1);
				_g_free0 (Image);
				_g_free0 (Id);
				_json_object_unref0 (o);
				__vala_JsonNode_free0 (c);
			}
		}
		_g_list_free0 (c_collection);
	}
	_json_array_unref0 (jsonContainers);
	_g_object_unref0 (parser);
	_g_object_unref0 (message);
	_g_object_unref0 (session);
	_g_free0 (uri);
}


static void docker_gui_get_selection (GtkTreeModel* model, GtkTreeIter* iter, DockerGuiContainer* result) {
	DockerGuiContainer c = {0};
	GtkTreeModel* _tmp0_ = NULL;
	GtkTreeIter _tmp1_ = {0};
	g_return_if_fail (model != NULL);
	g_return_if_fail (iter != NULL);
	memset (&c, 0, sizeof (DockerGuiContainer));
	_tmp0_ = model;
	_tmp1_ = *iter;
	gtk_tree_model_get (_tmp0_, &_tmp1_, 0, &c.Id, 1, &c.Image, -1);
	*result = c;
	return;
}


static void docker_gui_on_row_activated (DockerGui* self, GtkTreeView* treeview, GtkTreePath* path, GtkTreeViewColumn* column) {
	GtkTreeIter iter = {0};
	GtkTreeView* _tmp0_ = NULL;
	GtkTreeModel* _tmp1_ = NULL;
	GtkTreeModel* _tmp2_ = NULL;
	GtkTreePath* _tmp3_ = NULL;
	GtkTreeIter _tmp4_ = {0};
	gboolean _tmp5_ = FALSE;
	g_return_if_fail (self != NULL);
	g_return_if_fail (treeview != NULL);
	g_return_if_fail (path != NULL);
	g_return_if_fail (column != NULL);
	_tmp0_ = treeview;
	_tmp1_ = gtk_tree_view_get_model (_tmp0_);
	_tmp2_ = _tmp1_;
	_tmp3_ = path;
	_tmp5_ = gtk_tree_model_get_iter (_tmp2_, &_tmp4_, _tmp3_);
	iter = _tmp4_;
	if (_tmp5_) {
		DockerGuiContainer c = {0};
		GtkTreeView* _tmp6_ = NULL;
		GtkTreeModel* _tmp7_ = NULL;
		GtkTreeModel* _tmp8_ = NULL;
		GtkTreeIter _tmp9_ = {0};
		DockerGuiContainer _tmp10_ = {0};
		FILE* _tmp11_ = NULL;
		gchar* _tmp12_ = NULL;
		gchar* _tmp13_ = NULL;
		gchar* _tmp14_ = NULL;
		gchar* _tmp15_ = NULL;
		_tmp6_ = treeview;
		_tmp7_ = gtk_tree_view_get_model (_tmp6_);
		_tmp8_ = _tmp7_;
		_tmp9_ = iter;
		docker_gui_get_selection (_tmp8_, &_tmp9_, &_tmp10_);
		c = _tmp10_;
		_tmp11_ = stdout;
		_tmp12_ = docker_gui_container_to_string (&c);
		_tmp13_ = _tmp12_;
		_tmp14_ = g_strconcat ("GO ", _tmp13_, "\n", NULL);
		_tmp15_ = _tmp14_;
		fprintf (_tmp11_, "%s", _tmp15_);
		_g_free0 (_tmp15_);
		_g_free0 (_tmp13_);
		docker_gui_container_destroy (&c);
	}
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


static void docker_gui_on_selection (DockerGui* self, GtkTreeSelection* selection) {
	GtkTreeModel* model = NULL;
	GtkTreeIter iter = {0};
	GtkTreeSelection* _tmp0_ = NULL;
	GtkTreeModel* _tmp1_ = NULL;
	GtkTreeIter _tmp2_ = {0};
	gboolean _tmp3_ = FALSE;
	GtkTreeModel* _tmp4_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (selection != NULL);
	_tmp0_ = selection;
	_tmp3_ = gtk_tree_selection_get_selected (_tmp0_, &_tmp1_, &_tmp2_);
	_g_object_unref0 (model);
	_tmp4_ = _g_object_ref0 (_tmp1_);
	model = _tmp4_;
	iter = _tmp2_;
	if (_tmp3_) {
		DockerGuiContainer c = {0};
		GtkTreeModel* _tmp5_ = NULL;
		GtkTreeIter _tmp6_ = {0};
		DockerGuiContainer _tmp7_ = {0};
		FILE* _tmp8_ = NULL;
		gchar* _tmp9_ = NULL;
		gchar* _tmp10_ = NULL;
		gchar* _tmp11_ = NULL;
		gchar* _tmp12_ = NULL;
		_tmp5_ = model;
		_tmp6_ = iter;
		docker_gui_get_selection (_tmp5_, &_tmp6_, &_tmp7_);
		c = _tmp7_;
		_tmp8_ = stdout;
		_tmp9_ = docker_gui_container_to_string (&c);
		_tmp10_ = _tmp9_;
		_tmp11_ = g_strconcat ("WARM ", _tmp10_, "\n", NULL);
		_tmp12_ = _tmp11_;
		fprintf (_tmp8_, "%s", _tmp12_);
		_g_free0 (_tmp12_);
		_g_free0 (_tmp10_);
		docker_gui_container_destroy (&c);
	}
	_g_object_unref0 (model);
}


gint docker_gui_main (gchar** args, int args_length1) {
	gint result = 0;
	DockerGui* dockerGui = NULL;
	DockerGui* _tmp0_ = NULL;
	gtk_init (&args_length1, &args);
	_tmp0_ = docker_gui_new ();
	g_object_ref_sink (_tmp0_);
	dockerGui = _tmp0_;
	gtk_widget_show_all ((GtkWidget*) dockerGui);
	gtk_main ();
	result = 0;
	_g_object_unref0 (dockerGui);
	return result;
}


int main (int argc, char ** argv) {
#if !GLIB_CHECK_VERSION (2,32,0)
	g_thread_init (NULL);
#endif
#if !GLIB_CHECK_VERSION (2,35,0)
	g_type_init ();
#endif
	return docker_gui_main (argv, argc);
}


static const gchar* string_to_string (const gchar* self) {
	const gchar* result = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	result = self;
	return result;
}


static gchar* docker_gui_container_to_string (DockerGuiContainer *self) {
	gchar* result = NULL;
	const gchar* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	const gchar* _tmp2_ = NULL;
	const gchar* _tmp3_ = NULL;
	gchar* _tmp4_ = NULL;
	_tmp0_ = (*self).Id;
	_tmp1_ = string_to_string (_tmp0_);
	_tmp2_ = (*self).Image;
	_tmp3_ = string_to_string (_tmp2_);
	_tmp4_ = g_strconcat (_tmp1_, ", ", _tmp3_, NULL);
	result = _tmp4_;
	return result;
}


static void docker_gui_container_copy (const DockerGuiContainer* self, DockerGuiContainer* dest) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	const gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	_tmp0_ = (*self).Id;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 ((*dest).Id);
	(*dest).Id = _tmp1_;
	_tmp2_ = (*self).Image;
	_tmp3_ = g_strdup (_tmp2_);
	_g_free0 ((*dest).Image);
	(*dest).Image = _tmp3_;
}


static void docker_gui_container_destroy (DockerGuiContainer* self) {
	_g_free0 ((*self).Id);
	_g_free0 ((*self).Image);
}


static DockerGuiContainer* docker_gui_container_dup (const DockerGuiContainer* self) {
	DockerGuiContainer* dup;
	dup = g_new0 (DockerGuiContainer, 1);
	docker_gui_container_copy (self, dup);
	return dup;
}


static void docker_gui_container_free (DockerGuiContainer* self) {
	docker_gui_container_destroy (self);
	g_free (self);
}


static GType docker_gui_container_get_type (void) {
	static volatile gsize docker_gui_container_type_id__volatile = 0;
	if (g_once_init_enter (&docker_gui_container_type_id__volatile)) {
		GType docker_gui_container_type_id;
		docker_gui_container_type_id = g_boxed_type_register_static ("DockerGuiContainer", (GBoxedCopyFunc) docker_gui_container_dup, (GBoxedFreeFunc) docker_gui_container_free);
		g_once_init_leave (&docker_gui_container_type_id__volatile, docker_gui_container_type_id);
	}
	return docker_gui_container_type_id__volatile;
}


static void docker_gui_class_init (DockerGuiClass * klass) {
	docker_gui_parent_class = g_type_class_peek_parent (klass);
}


static void docker_gui_instance_init (DockerGui * self) {
}


GType docker_gui_get_type (void) {
	static volatile gsize docker_gui_type_id__volatile = 0;
	if (g_once_init_enter (&docker_gui_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (DockerGuiClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) docker_gui_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (DockerGui), 0, (GInstanceInitFunc) docker_gui_instance_init, NULL };
		GType docker_gui_type_id;
		docker_gui_type_id = g_type_register_static (gtk_window_get_type (), "DockerGui", &g_define_type_info, 0);
		g_once_init_leave (&docker_gui_type_id__volatile, docker_gui_type_id);
	}
	return docker_gui_type_id__volatile;
}



